Module Module1
    Public INDEX As Byte = 0
    Public ETAPA(12)
    Public EQUIPO(12)
    Public KM(12)
    Public TIEMPO(12)
    Public NACIONALIDAD(12)
    Public PENALIZACION(12)
    Public TOTALTIEMPO(12)
    Public Const PENALIZACION1 = 30
    Public Const PENALIZACION2 = 40
    Public Const PENALIZACION3 = 50
    Public Const RECOMPENSA1 = 15
    Public Const RECOMPENSA2 = 10
    Public I As Byte

    Sub PENALIZACIONRECOMPENSA()
        If TIEMPO(INDEX) > 120 Then
            PENALIZACION(INDEX) = PENALIZACION1
            TOTALTIEMPO(INDEX) = TIEMPO(INDEX) + PENALIZACION(INDEX)
        ElseIf TIEMPO(INDEX) > 140 Then
            PENALIZACION(INDEX) = PENALIZACION2
            TOTALTIEMPO(INDEX) = TIEMPO(INDEX) + PENALIZACION(INDEX)
        ElseIf TIEMPO(INDEX) > 160 Then
            PENALIZACION(INDEX) = PENALIZACION3
            TOTALTIEMPO(INDEX) = TIEMPO(INDEX) + PENALIZACION(INDEX)
        ElseIf TIEMPO(INDEX) > 85 And EQUIPO(INDEX) = "MOVISTAR" Then
            PENALIZACION(INDEX) = RECOMPENSA1
            TOTALTIEMPO(INDEX) = TIEMPO(INDEX) - PENALIZACION(INDEX)
        ElseIf TIEMPO(INDEX) > 85 And EQUIPO(INDEX) = "PRO TEAM" Then
            PENALIZACION(INDEX) = RECOMPENSA2
            TOTALTIEMPO(INDEX) = TIEMPO(INDEX) - PENALIZACION(INDEX)
        Else
            PENALIZACION(INDEX) = 0
            TOTALTIEMPO(INDEX) = TIEMPO(INDEX) - PENALIZACION(INDEX)
        End If


    End Sub


End Module
